name: lets-plot-examples
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.10
  - bs4
  - cairosvg
  - cartopy
  - colorcet
  - fiona
  - geopandas
  - gdal=3.5.0
  - jupyter
  - kotlin-jupyter-kernel
  - networkx
  - numpy
  - overpy
  - pandas
  - pillow
  - pip
  - plotnine
  - polars
  - pyarrow
  - pyshp
  - rasterio
  - selenium
  - shapely
  - squarify
  - statsmodels
  - pip:
    - lets-plot
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - scikit-learn
