name: lets-plot-examples
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.10
  - colorcet
  - geopandas
  - jupyter
  - kotlin-jupyter-kernel
  - networkx
  - numpy
  - overpy
  - pandas
  - pillow
  - pip
  - pyarrow
  - pyshp
  - selenium
  - shapely
  - squarify
  - bs4
  - cairosvg
  - fiona
  - cartopy
  - rasterio
  - statsmodels
  - polars
  - plotnine
  - pip:
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - lets-plot
    - scikit-learn
