name: lets-plot-examples
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.8
  - colorcet
  - geopandas
  - jupyter
  - kotlin-jupyter-kernel
  - networkx
  - numpy
  - overpy
  - pandas
  - pillow
  - pip
  - pyarrow
  - selenium
  - shapely
  - squarify
  - pip:
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - lets-plot
    - scikit-learn