name: lets-plot-examples
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas=0.8.*
  - google-cloud-bigquery=1.24.*
  - jupyter=1.0.*
  - jupyterlab=2.2.*
  - networkx=2.4.*
  - numpy=1.18.*
  - overpy=0.4
  - pandas=1.0.*
  - pillow=7.1.*
  - pip
  - selenium=3.141.*
  - pip:
    - lets-plot==1.5.0
    - sklearn