name: lets-plot-examples
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas=0.*
  - google-cloud-bigquery=1.*
  - jupyter=1.*
  - jupyterlab=2.*
  - networkx=2.*
  - numpy=1.*
  - overpy=0.*
  - pandas=1.*
  - pillow=7.*
  - pip
  - selenium=3.*
  - squarify=0.*
  - pip:
    - lets-plot==1.5.2
    - sklearn