name: lets-plot-examples
channels:
  - conda-forge
dependencies:
  - python=3.7
  - colorcet
  - geopandas
  - jupyter
  - networkx
  - numpy
  - overpy
  - pandas
  - pillow
  - pip
  - pyarrow
  - selenium
  - squarify
  - pip:
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - sklearn